export const ORDER_STATUSES = {
  ORDER_RECEIVED: "ORDER_RECEIVED",
  PREPARING: "PREPARING",
  OUT_FOR_DELIVERY: "OUT_FOR_DELIVERY",
  DELIVERED: "DELIVERED"
};

export const STATUS_FLOW = [
  ORDER_STATUSES.ORDER_RECEIVED,
  ORDER_STATUSES.PREPARING,
  ORDER_STATUSES.OUT_FOR_DELIVERY,
  ORDER_STATUSES.DELIVERED
];
